version: '3.9'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000 #localhost:Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db

  db:
      image: mysql:8.0
      restart: always
      environment:
        MYSQL_DATABASE: main
        MYSQL_USER: norkos
        MYSQL_PASSWORD: norkos
        MYSQL_ROOT_PASSWORD: norkos
      volumes:
        - .dbdata:/var/lib/mysql
      ports:
        - 33067:3306